inhibit_all_warnings!
install! 'cocoapods', :deterministic_uuids => false
use_frameworks!

target 'KMCAirStreamerDemo_iOS' do
  pod 'GPUImage'
  pod 'libksygpulive/libksygpulive', '~> 2.6.1'
  pod 'CocoaAsyncSocket', '7.4.1'
  pod 'KMCAirStreamer', :path => '../'
end
